### ISSUE TITLE
File Mmul_8.0.1_chroms_w_lambda.fa-GtoA.ind.25 Cannot be opened ....

### ISSUE THREAD

**Issue by elisabethgoldman** [GuoliangLi-HZAU/BatMeth2#10]
Hi, 
I am encountering the error "Mmul_8.0.1_chroms_w_lambda.fa-GtoA.ind.25 Cannot be opened ..." when trying to run batmeth2 align. The Mmul_8.0.1_chroms_w_lambda.fa-GtoA files are present in the indexed reference genome directory, although none have the suffix "ind.25". I've attached a screenshot of the run log with the error. Any help is appreciated! 

![image](https://user-images.githubusercontent.com/26236435/63063090-1bb6d800-beb0-11e9-9539-2915c3bb6ece.png)

**Comment by SowmyaPulapet** [comment]
Hey, 

I am facing the same issue mentioned here. I hope you could solve the issue. If so, could you please help me ?
