### ISSUE TITLE
more advantages than bismark ?

### ISSUE THREAD

**Issue by hmyh1202** [GuoliangLi-HZAU/BatMeth2#2]
Does this soft more accurate than bismark ?

**Comment by GuoliangLi-HZAU** [comment]
1. more easy use and auto run pipeline, contain alignment, calculate methy level, gff annotation, visualization, dm analysis.
2. we can get more indel-hit while reads alignment.
3. btw, u also can use bismark, bwa, bsmap etc other aligners with --aligner= parameter.

Thanks.
