### ISSUE TITLE
Fatal error: glibc detected an invalid stdio handle!

### ISSUE THREAD

**Issue by cheehowteo** [GuoliangLi-HZAU/BatMeth2#5]
Dear Prof. Guoliang,

I tried to use the test data from your team to run BatMeth2 using my workstation Ubuntu 18.04.1 LTS Intel Xeon(R) CPU E3-1245 v5 ` 3.50GHz x 8. 

I builded the genome.fa index using build_index. Then I aligned the R1 and R2 reads using BatMeth2 align. First trial with BatMeth2 align was succesful but then BatMeth2 calmeth failed. Second attempt of BatMeth2 align failed with the following error message. 

[ Program directory ] /home/user/Downloads/BatMeth2/bin/
[ Program name ] BatMeth2
[ Workdir ] /home/user/Downloads/BatMeth2/test
[ outputdir ] ./
[ BatMeth2 ] Alignment R2.fq.gz ...
 >> ./meth1.sam.run.log 2>&1
/home/user/Downloads/BatMeth2/bin/batmeth2-align -g genome.fa -p 6 -i R2.fq.gz -o ./meth1.sam.sam >> ./meth1.sam.run.log 2>&1
Fatal error: glibc detected an invalid stdio handle

my command line is based on your TestDataUsagePipeline.pdf as followed BatMeth2 align -g genome.fa -i R1.fq.gz -i R2.fq.gz -p 6 -o meth1.sam

How can I solve this problem?

Thank you.

Best regards,
Teo
[meth1.sam.run.log](https://github.com/GuoliangLi-HZAU/BatMeth2/files/3006129/meth1.sam.run.log)

**Comment by GuoliangLi-HZAU** [comment]
I'm terribly sorry - the instructions for alignment are wrong. Please use - 1, - 2 parameters when specifying paired-ended data input files.
BatMeth2 align -g genome.fa -1 R1.fq.gz -2 R2.fq.gz -p 6 -o meth1.sam

**Comment by cheehowteo** [comment]
Dear Prof. Guoliang,

Thanks for the update.

Best regards,
Teo
